message:
  initial_message: |-
    物語を始めます。
    物語のジャンル（ファンタジー、SF、日常など）とテーマ（森で迷った少女、宇宙船が不時着、サーヴァント同士の対決など）を「ジャンル：テーマ」の形式で入力してください。（例 `ファンタジー：森で迷った少女`）
  ending_message: タイトル「｛タイトル｝」いかがでしたでしょうか。またのご利用をお待ちしております。
  error_message: 
    input_error01: 形式が誤っています。「ジャンル：テーマ」の形式で入力してください。（例 `ファンタジー：森で迷った少女`）

prompt:
  intro_prompt: |-
    あなたはプロのストーリーテラーです。
    以下の情報に基づいて、魅力的で続きが気になる物語の導入部分、さらにユーザーが選択できる3つの行動選択肢を提示してください。

    ジャンル: ｛ジャンル｝
    テーマ: ｛テーマ｝
    文字数: 200文字程度
    出力形式: {"物語":"物語の内容","選択肢":["選択肢1","選択肢2","選択肢3"]}のJSON形式

  nomal_prompt: |-
    あなたはプロのストーリーテラーです。
    ユーザーの選択と以下の条件に基づいて、物語の次の展開を生成し、さらにユーザーが選択できる3つの行動選択肢を提示してください。

    現在のストーリーの状況:｛これまでのストーリー｝
    ユーザーの選択:｛ユーザーの選択｝
    文字数: 200文字程度
    出力形式: {"物語":"物語の内容","選択肢":["選択肢1","選択肢2","選択肢3"]}のJSON形式

  climax_prompt: |-
    あなたはプロのストーリーテラーです。
    ユーザーの選択と以下の条件に基づいて、物語のクライマックスの展開を生成し、さらにユーザーが選択できる最後の3つの行動選択肢を提示してください。

    現在のストーリーの状況:｛これまでのストーリー｝
    ユーザーの選択:｛ユーザーの選択｝
    文字数: 200文字程度
    出力形式: {"物語":"物語の内容","選択肢":["選択肢1","選択肢2","選択肢3"]}のJSON形式

  ending_prompt: |-
    あなたはプロのストーリーテラーです。
    ユーザーの選択と以下の条件に基づいて、物語の結末を生成してください。

    現在のストーリーの状況:｛これまでのストーリー｝
    ユーザーの選択:｛ユーザーの選択｝
    文字数: 200文字程度
    出力形式: {"物語":"物語の内容"}のJSON形式

  title_prompt: |-
    あなたはプロのストーリーテラーです。
    以下の物語にタイトルをつけてください。

    物語の内容:｛物語の内容｝
    出力形式: {"title":"タイトルの内容"}のJSON形式